name: build 

on:

  workflow_dispatch:
  workflow_call:
  push:

jobs:

  build-kernel:

    runs-on: ubuntu-latest

    steps:

      - name: Setup environment
        run: sudo apt -y install libncurses5-dev libncurses-dev libssl-dev device-tree-compiler bc cpio lib32ncurses5-dev lib32z1 build-essential binutils bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev git aria2 
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./msm-4.19
          ref: rebase
          
      - name: Pull toolchain

        run: |

          cd $HOME

          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64-linux-android-4.9

          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9

      - name: Pull clang

        run: |
          
          cd $HOME

          git clone https://github.com/dpkg123/clang --depth=2

      - name: Build
        run: cd msm-4.19 && bash build.sh
      - name: cat config
        run: cd msm-4.19 && cat out/.config
